services:
  app-postgres:
      image: postgres:17
      container_name: app-postgres
      volumes:
        - app-postgres-db-volume:/var/lib/postgresql/data
      ports:
        - "14432:5432"
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 1234
        POSTGRES_DB: vacstorage
      healthcheck:
        test: ["CMD", "pg_isready", "-U", "postgres", "-d", "vacstorage"]
        interval: 10s
        retries: 5
        start_period: 5s

  flyway:
    image: flyway/flyway
    command: -connectRetries=60 migrate
    environment:
      FLYWAY_URL: jdbc:postgresql://app-postgres:5432/vacstorage
      FLYWAY_USER: postgres
      FLYWAY_PASSWORD: 1234
    volumes:
      - ../dataBase/_sql:/flyway/sql
    depends_on:
      app-postgres:
        condition: service_healthy

  postgres-exporter:
    image: bitnamilegacy/postgres-exporter:latest
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:1234@app-postgres:5432/vacstorage"
    ports:
      - "14187:9187"
    depends_on:
      - app-postgres

volumes:
  app-postgres-db-volume: