x-spark-common: 
  &spark-common
  build: .

services:
  spark-master:
    <<: *spark-common
    container_name: spark-master
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "12080:8080"
      # - "4040:4040" # debug

  spark-worker-1:
    <<: *spark-common
    container_name: spark-worker-1
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    network_mode: "service:datanode1"
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_LOCAL_HOSTNAME: datanode1
      SPARK_WORKER_WEBUI_PORT: 8081